<?php
$lang = array(
'install_lock_warning' => 'Waarschuwing: Uw installatie map is nog aanwezig op uw server',
'html_install_lock_removal' => 'yes',
'install_lock_removal' => 'Verwijder de map uit veiligheidsoverwegingen van uw server d.m.v. een FTP programma.',
'checksum_changed_warning' => 'E&eacute;n of meer bestanden zijn veranderd:',
'checksum_changed_accept' => 'Wijzigingen Doorvoeren',
'checksum_email_subject' => 'Een hoofdbestand is gewijzigd op uw website.',
'checksum_email_message' => 'ExpressionEngine heeft een verandering aan een hoofdbestand gedeteceerd op: {url}  De volgende bestanden zijn gewijzigd: {changed}  Als u deze wijzigingen heeft gemaakt, accepteer deze dan op de homepage van het control panel.  Als u deze wijzigingen niet heeft doorgevoerd kan het zijn dat u gehackt bent. Controleer de bestanden op verdachte inhoud (JavaScript or iFrames) en neem contact op met ExpressionEngine support: http://expressionengine.com/forums/viewcategory/4/  Bekijk de support policy voordat u een post plaatst op het forum: http://expressionengine.com/support/policy/',
'html_new_version_notice' => 'yes',
'new_version_notice' => 'ExpressionEngine versie %s is nu beschikbaar. Download <a href=\'%s\' title=\'Download Hier\'>hier</a> en volg de <a href=\'%s\' title=\'Versie Update Docs\'>Versie Update Documentatie</a>.',
'html_new_version_notice_high_priority' => 'yes',
'new_version_notice_high_priority' => '<span style=\"font-size:18px;color:#3BA1DB;font-weight:bold\">Veiligheids Update Release</span><br /> Een ExpressionEngine versie %s, build %s is uitgekomen als een veiligheids release.  De laatste versie is: %s, en de laatste build is: %s.<br /><br /> Download alstublieft <a href=\"%s\" title=\"Download Hier\">hier</a> en volg de <a href=\"%s\" title=\"Update Documentatie\">update documentatie</a> om zeker te zijn dat u de meest recente versie draait.',
'html_new_version_error' => 'yes',
'new_version_error' => 'Er is een onverwachte fout opgetreden bij het downloaden van het huidige ExpressionEngine versie nummer. Bezoek uw <a href=\'%s\' title=\'download account\'>Download Account</a> om de controleren of u over de recentste versie beschikt. Als deze fout blijft optreden, neem dan contact op met uw beheerder.',
'important_messages' => 'Opmerking',
'cp_home' => 'Mijn Homepage',
'current_user' => 'Huidige Gebruiker',
'system_status' => 'Systeem Status',
'offline' => 'Offline',
'online' => 'Online',
'member_search' => 'Leden Zoeken',
'search_instructions' => 'Voer een volledig of gedeeltelijk woord in',
'member_group' => 'Leden Groep',
'search_by' => 'Zoek Veld',
'screen_name' => 'Schermnaam',
'email_address' => 'E-mailadres',
'url' => 'URL',
'site_statistics' => 'Site Statistieken',
'value' => 'Waarde',
'total_members' => 'Totaal aantal Leden',
'total_validating_members' => 'Leden wachtend op activatie',
'total_validating_comments' => 'Reacties wachtend op activatie',
'total_entries' => 'Totaal aantal Berichten',
'total_comments' => 'Totaal Aantal Reacties',
'most_recent_entries' => 'Meest Recente Bericht',
'most_recent_comments' => 'Meest Recente Reactie',
'no_comments' => 'Er zijn op dit moment geen reacties',
'no_entries' => 'Er zijn op dit moment geen berichten',
'entry_title' => 'Bericht Titel',
'comments' => 'Reacties',
'no_channels_exist' => 'Er zijn op dit moment geen Channels',
'html_no_templates_available' => 'yes',
'no_templates_available' => 'Geen Templates Beschikbaar. <a href=\'%s\' title=\'Create a template group\'>Create a Template Group</a>',
'select_channel_to_post_in' => 'Kies een Channel om in te plaatsen',
'recent_members' => 'Meest Recente Nieuwe Leden',
'join_date' => 'Inschrijfdatum',
'total_hits' => 'Totaal aantal gecombineerde paginahits ',
'demo_expiration' => 'Uw demoaccount zal verlopen over:',
'bulletin_board' => 'Bulletin Bord',
'no_bulletins' => 'Geen Bulletins',
'bulletin_sender' => 'Bulletin Afzender',
'bulletin_date' => 'Bulletin Datum',
'exact_match' => 'Exacte Match',
'no_news' => 'Geen Nieuws Beschikbaar',
'more_news' => 'Meer Nieuws...',
'site_status' => 'Site Status',
'close' => 'Sluit',
'html_developer_logs' => 'yes',
'developer_logs' => 'Je hebt %d niet not gelezen items in de <a href=\"%s\">Developer Log</a>.',
'html_version_mismatch' => 'yes',
'version_mismatch' => 'Je ExpressionEngine installatie versie (%s) komt niet overeen met de gerapporteerde versie (%s). <a href=\"http://expressionengine.com/user_guide/installation/update.html\">Update je ExpressionEngine installatie nogmaals</a>.',
''=>''
    );